version: '3'
services:
  mongoDB:
    image: 'mongo'
    container_name: 'dev-mongo'
    environment:
      - MONGO_INITDB_DATABASE=devmongo
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - '27017-27019:27017-27019'
