version: '3'

services:

  backend:
    container_name: storj-images-backend-container
    image: registry.santiagorincon.tk/storj-images-backend
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
       - PORT=8080
       - ENV=prod
       - MONGO_USER=${MONGO_USER}
       - MONGO_PASS=${MONGO_PASS}
       - MONGO_URL=${MONGO_URL}
       - TOKEN_STORJ=${TOKEN_STORJ}
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8080:8080"


  mongodb:
    container_name: storj-images-mongodb-container
    image: mongo:latest
    volumes:
      - /var/lib/mongo:/data/db
    restart: unless-stopped


networks:
  default:
    name: storj-images-network
