version: '3'

services:
  backend:
    container_name: storj-images-backend-container
    image: registry.santiagorincon.tk/storj-images-backend
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
       - PORT=8080
       - ENV=prod
       - MONGO_USER=${MONGO_USER}
       - MONGO_PASS=${MONGO_PASS}
       - MONGO_URL=mongodb://storj-images-mongodb-container:27017
       - TOKEN_STORJ=${TOKEN_STORJ}
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8080:8080"

  mongodb:
    container_name: storj-images-mongodb-container
    image: mongo:6.0.3
    restart: "no"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345

networks:
  default:
    name: storj-images-network
