version: '3'

services:
  backend:
    container_name: storj-images-backend-container
    image: registry.santiagorincon.tk/storj-images-backend
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
       - PORT=8080
       - ENV=develop
       - MONGO_USER=root
       - MONGO_PASS=12345
       - MONGO_URL=mongodb://storj-images-mongodb-container:27017
       - TOKEN_STORJ=${TOKEN_STORJ}
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 10M

  mongodb:
    container_name: storj-images-mongodb-container
    image: mongo:6.0.3
    restart: "no"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
         - /var/lib/mongo_dev:/data/db
    deploy:
      resources:
        limits:
          memory: 600M
        reservations:
          memory: 100M

networks:
  default:
    name: storj-images-network
