# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  nolintlint:
    # Disable to ensure that all nolint directives actually have an effect. Default is false.
    allow-unused: false
    # Disable to ensure that nolint directives don't have a leading space. Default is true.
    allow-leading-space: true
    # Exclude following linters from requiring an explanation.  Default is [].
    allow-no-explanation: [ ]
    # Enable to require an explanation of nonzero length after each nolint directive. Default is false.
    require-explanation: true
    # Enable to require nolint directives to mention the specific linter being suppressed. Default is false.
    require-specific: true

  funlen:
    lines: 60
    statements: 40

  ifshort:
    # Maximum length of variable declaration measured in number of lines, after which linter won't suggest using short syntax.
    # Has higher priority than max-decl-chars.
    max-decl-lines: 1
    # Maximum length of variable declaration measured in number of characters, after which linter won't suggest using short syntax.
    max-decl-chars: 30

  varnamelen:
    # The longest distance, in source lines, that is being considered a "small scope." (defaults to 5)
    # Variables used in at most this many lines will be ignored.
    max-distance: 5
    # The minimum length of a variable's name that is considered "long." (defaults to 3)
    # Variable names that are at least this long will be ignored.
    min-name-length: 3
    # Check method receiver names. (defaults to false)
    check-receiver: true
    # Check named return values. (defaults to false)
    check-return: true
    # Ignore "ok" variables that hold the bool return value of a type assertion. (defaults to false)
    ignore-type-assert-ok: false
    # Ignore "ok" variables that hold the bool return value of a map index. (defaults to false)
    ignore-map-index-ok: false
    # Ignore "ok" variables that hold the bool return value of a channel receive. (defaults to false)
    ignore-chan-recv-ok: false
    # Optional list of variable names that should be ignored completely. (defaults to empty list)
    ignore-names:
      - err
    # Optional list of variable declarations that should be ignored completely. (defaults to empty list)
    # Entries must be in the form of "<variable name> <type>" or "<variable name> *<type>" for
    # variables, or "const <name>" for constants.
    ignore-decls:
      - c *gin.Context
      - t testing.T
      - ctx *gin.Context
      - e error


linters:
  enable:
    - errcheck
    - revive
    - govet
    - staticcheck
    - unused
    - wsl
    - unused
    - typecheck
    - dupl
    - funlen
    - gocritic
    - godot
    - godox
    - gomnd
    - gosec
    - lll
    - makezero
    - nlreturn
    - tparallel
    - prealloc
    - unconvert
    - nolintlint
    - gci
    - ifshort
    - gofumpt
    - misspell
    - nestif
    - nilerr
    - testpackage
    - unused
    - whitespace

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - wsl