database:
  ids:
    url_env: 'MONGO_URL'
    database: 'storj'
    collection: 'images'
    user_env: 'MONGO_USER'
    password_env: 'MONGO_PASS'
  photos:
    project: 'Images golang'
    bucket: 'prod'
    token_env: 'TOKEN_STORJ'

image:
  allowed_formats:
    - .png
    - .jpg
